---
- name: Retrieve secret from AWS Secrets Manager
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - amazon.aws

  vars:
    secret_name: "prod/webapp/rds"
    region: "us-east-1"

  tasks:
    - name: Look up secret value
      ansible.builtin.set_fact:
        secret_value: "{{ lookup('amazon.aws.secretsmanager_secret', secret_name, region=region) | from_json }}"

    - name: Show parsed secret
      ansible.builtin.debug:
        msg:
          - "Username: {{ secret_value.username }}"
          - "Password: {{ secret_value.password }}"
